### ISSUE TITLE
add a license statement to project

### ISSUE THREAD

**Issue by HamletDRC** [andrew-w-ross/typings-react-redux#3]
can you please add a license statement to your readme.md file.

**Comment by vslinko** [comment]
I prefer MIT License. @andrew-w-ross what are you think?

**Comment by andrew-w-ross** [comment]
@vslinko MIT all the way.

**Comment by vslinko** [comment]
Closed by https://github.com/andrew-w-ross/typings-react-redux/commit/7350ae03b5e0b657d3d55a974fa74d1ca9092761
